# Generated by Django 4.2.3 on 2023-07-09 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calenders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='calenders.calender', unique_for_date='post_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
